build:
    environment:
        php: '7.1.12'

    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
        tests: true
    tests:
        before:
            - bash .travis/install-wp-tests.sh wordpress_test root '' localhost latest
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - 'tests/*'
    dependency_paths:
        - wordpress/

checks:
    php:
        code_rating: true
        duplication: true
