env:
  global:
    - CC_TEST_REPORTER_ID=a99d3e2e2a89153a1035f6f2012cf35455fc1682f4e17e4e9dc8088f33c5ea11

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest

before_script:
  - composer update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash .travis/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit
      WP_MULTISITE=1 vendor/bin/phpunit --coverage-clover clover.xml
    fi

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT; fi
