name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Install WP Test Suite
        run: ./.github/install-wp-tests.sh wordpress_test root root localhost latest

      - name: Run tests
        run: vendor/bin/phpunit
      
      - name: Run tests in multi-site mode
        run: phpunit
        env:
          WP_MULTISITE: 1
